# Use postgres/example user/password credentials
version: "3.7"

services:
  db:
    image: postgres:14-alpine
    container_name: database
    restart: always
    environment:
      POSTGERS_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin2022
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: nfp@email.com
      PGADMIN_DEFAULT_PASSWORD: admin2022
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db